---
title: "Welcome to My Blog"
description: |
  This blog contains tutorial of MetDA website and some explanation of statistical analysis methods that are commonly used in metabolomics!
author:
  - name: West Coast Metabolomics Center 
    url: http://metabolomics.ucdavis.edu/
    affiliation: Fiehn Lab
    affiliation_url: http://fiehnlab.ucdavis.edu
date: 11-01-2018
output:
  radix::radix_article:
    self_contained: false
---

Similar to genomic and proteomic platforms, metabolomic data acquisition and analysis is becoming a routine approach for investigating biological systems. However, computational approaches for metabolomic data analysis and integration are still maturing. Metabox is a bioinformatics toolbox for deep phenotyping analytics that combines data processing, statistical analysis, functional analysis and integrative exploration of metabolomic data within proteomic and transcriptomic contexts. With the number of options provided in each analysis module, it also supports data analysis of other ‘omic’ families. The toolbox is an R-based web application, and it is freely available at http://kwanjeeraw.github.io/metabox/ under the GPL-3 license.

More Information check this: Metabox: A Toolbox for Metabolomic Data Analysis, Interpretation and Integrative Exploration https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0171046


If you are interested, welcome to contact us at http://fiehnlab.ucdavis.edu/








